---
title: "OrcAI: Overlap of Annotations"
format:
  html:
    toc: true
    toc-location: left
    code-fold: true
    code-overflow: wrap
    embed-resources: true
knitr:
  opts_chunk: 
    fig-width: 12
    fig-height: 7.5
# execute:
#   echo: false
#   warning: false
#   message: false
title-meta: "OrcAI: Overlap of Annotations"
author-meta: "Daniel Angst"
---

```{r}
#| label: load packages & fns
#| warning: false
library(tidyverse)
library(here)
library(glue)
library(jsonlite)
library(knitr)
library(kableExtra)
library(ivs)

source(here("analysis_scripts/annotation_overlap_fns.R"))
```

# Load data

```{r}
#| label: load data
all_annotations <- read_csv(here("data/all_annotations.csv"),
    col_types = cols(
        recording = col_character(),
        start = col_double(),
        stop = col_double(),
        label = col_character()
    )
)

all_predictions <- read_csv(
    here("data/all_predictions.csv"),
    col_types = cols(
        recording = col_character(),
        start = col_double(),
        stop = col_double(),
        label = col_character(),
        mean_p = col_double(),
        label_source = col_character()
    )
)
```

# Annotations & Predictions

```{r}
#| label: annotation duration
mean_annotation_duration <- all_annotations |>
    ungroup() |>
    mutate(
        duration = stop - start
    ) |>
    group_by(
        label
    ) |>
    summarize(
        ens = n(),
        min = min(duration),
        max = max(duration),
        mean = mean(duration),
        sd = sd(duration),
        se = sd / sqrt(ens),
        margin = qt(0.975, df = ens - 1) * se,
        ci95_lower = mean - margin,
        ci95_upper = mean + margin,
        sum = sum(duration)
    ) |>
    select(-margin) |>
    mutate(
        label_abbr = label,
        label = case_match(
            label,
            "BR" ~ "breathing",
            "BUZZ" ~ "buzzing",
            "HERDING" ~ "herding calls",
            "PHS" ~ "prey handling sounds",
            "SS" ~ "pulsed calls",
            "TAILSLAP" ~ "tail slaps",
            "WHISTLE" ~ "whistles",
        ),
        .before = "label"
    )

kable(mean_annotation_duration, caption = "Duration of Annotations by Type", digits = 3)

annotation_filter_duration <- mean_annotation_duration |>
    mutate(
        min_filter = c(0.4, 0.05, 1.00, 0.1, 0.05, 0.05, 0.1),
        max_filter = "Inf"
    ) |>
    select(
        label_abbr, label, min, max, min_filter, max_filter
    )

annotation_filter_duration |>
    kbl(
        format = "latex", digits = 4,
        booktabs = TRUE, linesep = "",
        col.names = c("Label (Abbr.)", "Label", "min", "max", "min", "max")
    ) |>
    add_header_above(c(" " = 2, "obeserved duration [s]" = 2, "filtered duration [s]" = 2)) |>
    write_lines(file = here("analysis_scripts", "output", "tex", "annotation_filter_duration.tex"))

annotation_duration <- mean_annotation_duration |>
    mutate(
        total_duration = seconds_to_hhmmss(sum)
    ) |>
    select(
        label, total_duration, ens
    )

annotation_duration |>
    kbl(
        format = "latex", digits = 4,
        booktabs = TRUE, linesep = "",
        col.names = c("Accoustic Signal", "Total duration", "Number")
    ) |>
    write_lines(file = here("analysis_scripts", "output", "tex", "annotation_duration.tex"))


```

```{r}
#| label: prediction duration
mean_prediction_duration <- all_predictions |>
    ungroup() |>
    mutate(
        duration = stop - start
    ) |>
    group_by(
        label
    ) |>
    summarize(
        ens = n(),
        min = min(duration),
        max = max(duration),
        mean = mean(duration),
        sd = sd(duration),
        se = sd / sqrt(ens),
        margin = qt(0.975, df = ens - 1) * se,
        ci95_lower = mean - margin,
        ci95_upper = mean + margin
    ) |>
    select(-margin)
kable(mean_prediction_duration, caption = "Duration of Predictions by Type", digits = 3)
```

# Overlaps
```{r}
#| label: count overlaps
all_annotations_overlaps <- all_annotations |>
    group_by(recording) |>
    arrange(start, .by_group = TRUE) |>
    mutate(
        id = glue("{recording}_{seq_len(n())}"),
        count_overlaps(start, stop)
    )
write_csv(
    all_annotations_overlaps |>
        select(-overlaps_with_list),
    here("analysis_scripts", "output", "csv", "all_annotations_overlaps.csv")
)

all_predictions_overlaps <- all_predictions |>
    group_by(recording) |>
    arrange(start, .by_group = TRUE) |>
    mutate(
        id = glue("{recording}_{seq_len(n())}"),
        count_overlaps(start, stop)
    )
write_csv(
    all_predictions_overlaps |>
        select(-overlaps_with_list),
    here("analysis_scripts", "output", "csv", "all_predictions_overlaps.csv")
)

```

```{r}
#| label: annotations overlap summary
all_annotations_overlaps_summary <- all_annotations_overlaps |>
    ungroup() |>
    select(-overlaps_with) |>
    count(overlaps_with_n) |>
    mutate(
        total = sum(n),
        percent = 100 * (n / sum(n))
    )

write_csv(
    all_annotations_overlaps_summary,
    here("analysis_scripts", "output", "csv", "all_annotations_overlaps_summary.csv")
)

kable(all_annotations_overlaps_summary, caption = "Annotations: Summary of Overlaps")
```

```{r}
#| label: predictions overlap summary
all_predictions_overlaps_summary <- all_predictions_overlaps |>
    ungroup() |>
    select(-overlaps_with) |>
    count(overlaps_with_n) |>
    mutate(
        total = sum(n),
        percent = 100 * (n / sum(n))
    )

write_csv(
    all_predictions_overlaps_summary,
    here("analysis_scripts", "output", "csv", "all_predictions_overlaps_summary.csv")
)

kable(all_predictions_overlaps_summary, caption = "Predictions: Summary of Overlaps")
```

```{r}
#| label: annotation overlap duration
all_annotations_overlaps_duration <- all_annotations |>
    group_by(recording) |>
    summarise(
        annotation_duration = sum(stop - start),
        overlap_duration = recording_overlap_duration(start, stop),
        ratio = overlap_duration / annotation_duration
    )

write_csv(
    all_annotations_overlaps_duration,
    here("analysis_scripts", "output", "csv", "all_annotations_overlaps_duration.csv")
)

all_annotations_overlaps_duration_summary <- all_annotations_overlaps_duration |>
    summarize(
        total_annotation_duration = sum(annotation_duration),
        total_overlap_duration = sum(all_annotations_overlaps_duration$overlap_duration),
        ratio_with_overlap = total_overlap_duration / total_annotation_duration
    )

write_csv(
    all_annotations_overlaps_duration_summary,
    here("analysis_scripts", "output", "csv", "all_annotations_overlaps_duration_summary.csv")
)

kable(all_annotations_overlaps_duration_summary, caption = "Annotations: Total overlap duration")
```

```{r}
#| label: annotation overlap duration figure
#| fig-cap: "Distribution of overlap duration in annotations"

ggplot(
    data = all_annotations_overlaps_duration,
    mapping = aes(x = overlap_duration)
) +
    geom_histogram(binwidth = 1) +
    labs(x = "total duration with overlap [s]") +
    theme_bw()
```

```{r}
#| label: prediction overlap duration
all_predictions_overlaps_duration <- all_predictions |>
    group_by(recording) |>
    summarise(
        prediction_duration = sum(stop - start),
        overlap_duration = recording_overlap_duration(start, stop),
        ratio = overlap_duration / prediction_duration
    )

write_csv(
    all_predictions_overlaps_duration,
    here("analysis_scripts", "output", "csv", "all_predictions_overlaps_duration.csv")
)

all_predictions_overlaps_duration_summary <- all_predictions_overlaps_duration |>
    summarize(
        total_prediction_duration = sum(prediction_duration),
        total_overlap_duration = sum(all_predictions_overlaps_duration$overlap_duration),
        ratio_with_overlap = total_overlap_duration / total_prediction_duration
    )

write_csv(
    all_predictions_overlaps_duration_summary,
    here("analysis_scripts", "output", "csv", "all_predictions_overlaps_duration_summary.csv")
)

kable(all_predictions_overlaps_duration_summary, caption = "Predictions: Total overlap duration")
```

```{r}
#| label: prediction overlap duration figure
#| fig-cap: "Distribution of overlap duration in predictions"

ggplot(
    data = all_predictions_overlaps_duration,
    mapping = aes(x = overlap_duration)
) +
    geom_histogram(binwidth = 1) +
    labs(x = "total duration with overlap [s]") +
    theme_bw()
```

## prediction of overlaps

```{r}
#| label: prediction of overlaps

recordings_with_annotations <- unique(all_annotations_overlaps$recording)
predicted_annotations_list <- list()

for (i in seq_along(recordings_with_annotations)) {
    i_recording <- recordings_with_annotations[i]
    i_annotations <- filter(all_annotations_overlaps, recording == i_recording) |>
        mutate(iv = iv(start, stop))
    i_predictions <- filter(all_predictions_overlaps, recording == i_recording) |>
        mutate(iv = iv(start, stop))

    i_locations <- iv_locate_overlaps(i_annotations$iv, i_predictions$iv)

    locations_i_annotations <- i_annotations[i_locations$needles, ] |>
        ungroup() |>
        select(
            recording,
            annotation_id = id,
            annotation_start = start, annotation_stop = stop,
            annotation_label = label,
            annotation_overlaps_with = overlaps_with
        )
    locations_i_predictions <- i_predictions[i_locations$haystack, ] |>
        ungroup() |>
        select(
            prediction_id = id,
            prediction_start = start, prediction_stop = stop,
            prediction_label = label,
            prediction_overlaps_with = overlaps_with
        )

    # check if any of the overlapping prediction is true, only return those
    predicted_annotations_list[[i]] <- bind_cols(locations_i_annotations, locations_i_predictions) |>
        group_by(annotation_id) |>
        group_modify(
            resolve_multiple_overlaps
        )
}

predicted_annotations <- bind_rows(predicted_annotations_list)

prediction_of_annotations <- predicted_annotations |>
    ungroup() |>
    summarise(
        correct_prediction = sum(prediction_correct, na.rm = TRUE),
        incorrect_prediction = sum(!prediction_correct, na.rm = TRUE),
        no_prediction = sum(is.na(prediction_correct))
    ) |>
    pivot_longer(cols = everything(), values_to = "predictions", names_to = "n") |>
    mutate(total = sum(predictions), p = predictions / sum(predictions), pc = p * 100)

prediction_of_annotations |>
    kable(caption = "Number & proportion of annotations that were predicted")

prediction_of_annotations_without_overlaps <- predicted_annotations |>
    ungroup() |>
    filter(annotation_overlaps_with == "") |>
    summarise(
        correct_prediction = sum(prediction_correct, na.rm = TRUE),
        incorrect_prediction = sum(!prediction_correct, na.rm = TRUE),
        no_prediction = sum(is.na(prediction_correct))
    ) |>
    pivot_longer(cols = everything(), values_to = "predictions", names_to = "n") |>
    mutate(total = sum(predictions), p = predictions / sum(predictions), pc = p * 100)

prediction_of_annotations_without_overlaps |>
    kable(caption = "Number & proportion of annotations without overlap that were predicted")


prediction_of_annotations_with_overlaps <- predicted_annotations |>
    ungroup() |>
    filter(annotation_overlaps_with != "") |>
    summarise(
        correct_prediction = sum(prediction_correct, na.rm = TRUE),
        incorrect_prediction = sum(!prediction_correct, na.rm = TRUE),
        no_prediction = sum(is.na(prediction_correct))
    ) |>
    pivot_longer(cols = everything(), values_to = "predictions", names_to = "n") |>
    mutate(total = sum(predictions), p = predictions / sum(predictions), pc = p * 100)

prediction_of_annotations_with_overlaps |>
    kable(caption = "Number & proportion of annotations that have overlaps that were predicted")



write_csv(
    predicted_annotations,
    here("analysis_scripts", "output", "csv", "predicted_annotations.csv")
)



```

